//! Migrate command.

use crate::cli::*;

pub(crate) async fn migrate(args: MigrateArgs) -> ferrite::Result<()> {
    let text = std::fs::read_to_string(&args.file).map_err(|_| {
        ferrite::FerriteError::Config(format!("cannot read `{}`", args.file.display()))
    })?;
    let mut out = String::from("# Generated by `ferrite migrate` — review before use.\n\n");
    let mut warnings = Vec::new();
    // Best-effort key extraction (documented approximation).
    let get_str = |key: &str| {
        let pattern = format!(r#"{key}\s*:\s*["']([^"']+)["']"#);
        regex_extract(&text, &pattern)
    };
    let get_num = |key: &str| {
        let pattern = format!(r#"{key}\s*:\s*(\d+)"#);
        regex_extract(&text, &pattern)
    };
    let get_bool = |key: &str| {
        let pattern = format!(r#"{key}\s*:\s*(true|false)"#);
        regex_extract(&text, &pattern)
    };
    if let Some(port) = get_num("port") {
        out.push_str(&format!("[server]\nport = {port}\n"));
    }
    if let Some(host) = get_str("host") {
        if !out.contains("[server]") {
            out.push_str("[server]\n");
        }
        out.push_str(&format!("host = \"{host}\"\n"));
    }
    if let Some(dir) = get_str("outDir") {
        out.push_str(&format!("\n[build]\nout_dir = \"{dir}\"\n"));
    }
    if let Some(map) = get_bool("sourcemap").or_else(|| get_str("sourcemap")) {
        if !out.contains("[build]") {
            out.push_str("\n[build]\n");
        }
        out.push_str(&format!("sourcemap = {map}\n"));
    }
    if text.contains("plugins") {
        warnings.push("plugins: prefer Rust equivalents; JS plugins can run through the tier-2 host (`ferrite_plugin::js_host`, `--features napi-vm`, hooks resolveId/load/transform)");
    }
    if text.contains("defineConfig") {
        // fine
    }
    if text.contains("resolve") && text.contains("alias") {
        warnings.push("resolve.alias: migrate entries manually to [resolve.alias] (shapes vary)");
    }
    out.push_str("\n# Review: server.port/host, resolve.alias, define, css.modules,\n# build.outDir/sourcemap, ssr.external/noExternal.\n");
    match args.out {
        Some(path) => {
            std::fs::write(&path, &out)?;
            println!("wrote {}", path.display());
        }
        None => print!("{out}"),
    }
    for warning in warnings {
        println!("warning: {warning}");
    }
    Ok(())
}

pub(crate) fn regex_extract(text: &str, pattern: &str) -> Option<String> {
    // Minimal single-group matcher without the regex crate (CLI stays lean).
    let key = pattern
        .split("\\s")
        .next()?
        .trim_start_matches("r#\"")
        .to_string();
    for (index, _) in text.match_indices(&key) {
        // Word boundary: `port` must not match inside `export`.
        if index > 0 {
            let before = text.as_bytes()[index - 1] as char;
            if before.is_alphanumeric() || before == '_' || before == '$' {
                continue;
            }
        }
        let rest = &text[index + key.len()..];
        let rest = rest.trim_start_matches([' ', '\t', '\n', '\r', ':']);
        let rest = rest.trim_start();
        if rest.starts_with('"') || rest.starts_with('\'') {
            let quote = rest.as_bytes()[0] as char;
            if let Some(end) = rest[1..].find(quote) {
                return Some(rest[1..1 + end].to_string());
            }
        } else {
            let end = rest
                .find(|c: char| !(c.is_alphanumeric() || c == '.' || c == '_' || c == '-'))
                .unwrap_or(rest.len());
            if end > 0 {
                return Some(rest[..end].to_string());
            }
        }
    }
    None
}
